#if defined(NPSR_TRIG_EXTENDED_INL_H_) == defined(HWY_TARGET_TOGGLE)  // NOLINT
#ifdef NPSR_TRIG_EXTENDED_INL_H_
#undef NPSR_TRIG_EXTENDED_INL_H_
#else
#define NPSR_TRIG_EXTENDED_INL_H_
#endif

#include "npsr/hwy.h"
#include "npsr/trig/data/data.h"
#include "npsr/trig/low-inl.h"  // Operation

HWY_BEFORE_NAMESPACE();
namespace npsr::HWY_NAMESPACE::trig {

template <Operation OP, class V>
NPSR_INTRIN V Extended(V x) {
  using namespace hn;
  namespace data = ::npsr::trig::data;
  using hwy::ExponentBits;
  using hwy::MantissaBits;
  using hwy::MantissaMask;
  using hwy::SignMask;

  using D = DFromV<V>;
  using DI = RebindToSigned<D>;
  using DU = RebindToUnsigned<D>;
  using VI = Vec<DI>;
  using VU = Vec<DU>;
  using T = TFromV<V>;
  using TU = TFromV<VU>;
  const D d;
  const DI di;
  const DU du;

  constexpr bool kIsSingle = std::is_same_v<T, float>;

  // =============================================================================
  // PHASE 1: Table Lookup for Reduction Constants
  // =============================================================================
  // Each table entry contains 3 consecutive values [high, mid, low]
  // providing ~96-bit (F32) or ~192-bit (F64) precision for (4/π) × 2^exp
  VU u_exponent = GetBiasedExponent(x);
  VI i_table_idx =
      BitCast(di, Add(ShiftLeft<1>(u_exponent), u_exponent));  // × 2 + 1 = × 3

  // Gather three parts of (4/π) × 2^exp from precomputed table
  // Generated by npsr/trig/data/reduction.h.sol
  VU u_p_hi = GatherIndex(du, data::kLargeReductionTable<T>, i_table_idx);
  VU u_p_med = GatherIndex(du, data::kLargeReductionTable<T> + 1, i_table_idx);
  VU u_p_lo = GatherIndex(du, data::kLargeReductionTable<T> + 2, i_table_idx);

  // =============================================================================
  // PHASE 2: Extract and Normalize Mantissa
  // =============================================================================

  // Extract and Normalize Mantissa
  V abx = Abs(x);
  VU u_input = BitCast(du, abx);
  VU u_significand = And(u_input, Set(du, MantissaMask<T>()));
  // Add implicit leading 1 bit
  VU u_integer_bit =
      Or(u_significand, Set(du, static_cast<TU>(1) << MantissaBits<T>()));
  VU u_mantissa = Or(u_significand, u_integer_bit);

  // Split mantissa into halves for extended precision multiplication
  // F32: 16-bit halves, F64: 32-bit halves
  constexpr int kHalfShift = (sizeof(T) / 2) * 8;
  VU u_low_mask = Set(du, (static_cast<TU>(1) << kHalfShift) - 1);
  VU u_m0 = And(u_mantissa, u_low_mask);
  VU u_m1 = ShiftRight<kHalfShift>(u_mantissa);

  // Split reduction constants into halves
  VU u_p0 = And(u_p_lo, u_low_mask);
  VU u_p1 = ShiftRight<kHalfShift>(u_p_lo);
  VU u_p2 = And(u_p_med, u_low_mask);
  VU u_p3 = ShiftRight<kHalfShift>(u_p_med);
  VU u_p4 = And(u_p_hi, u_low_mask);
  VU u_p5 = ShiftRight<kHalfShift>(u_p_hi);

  // =============================================================================
  // PHASE 3: Extended Precision Multiplication
  // =============================================================================
  // mantissa × (4/π × 2^exp) using half-word multiplications
  // F32: 16×16→32 bit, F64: 32×32→64 bit multiplications

  // Products with highest precision part
  VU u_m04 = Mul(u_m0, u_p4);
  VU u_m05 = Mul(u_m0, u_p5);
  VU u_m14 = Mul(u_m1, u_p4);
  // Omit u_m1 × u_p5 to prevent overflow

  // Products with medium precision part
  VU u_m02 = Mul(u_m0, u_p2);
  VU u_m03 = Mul(u_m0, u_p3);
  VU u_m12 = Mul(u_m1, u_p2);
  VU u_m13 = Mul(u_m1, u_p3);

  // Products with lowest precision part
  VU u_m01 = Mul(u_m0, u_p1);
  VU u_m10 = Mul(u_m1, u_p0);
  VU u_m11 = Mul(u_m1, u_p1);

  // =============================================================================
  // PHASE 4: Carry Propagation and Result Assembly
  // =============================================================================
  // Extract carry bits from each product
  VU u_carry04 = ShiftRight<kHalfShift>(u_m04);
  VU u_carry02 = ShiftRight<kHalfShift>(u_m02);
  VU u_carry03 = ShiftRight<kHalfShift>(u_m03);
  VU u_carry01 = ShiftRight<kHalfShift>(u_m01);
  VU u_carry10 = ShiftRight<kHalfShift>(u_m10);

  // Extract lower halves
  VU u_low04 = And(u_m04, u_low_mask);
  VU u_low02 = And(u_m02, u_low_mask);
  VU u_low05 = And(u_m05, u_low_mask);
  VU u_low03 = And(u_m03, u_low_mask);

  // Column-wise accumulation (Intel SVML pattern)
  VU u_col3 = Add(u_low05, Add(u_m14, u_carry04));
  VU u_col2 = Add(u_low04, Add(u_m13, u_carry03));
  VU u_col1 = Add(u_low02, Add(u_m11, u_carry01));
  VU u_col0 = Add(u_low03, Add(u_m12, u_carry02));

  // Carry propagation through columns
  VU u_sum0 = Add(u_carry10, u_col1);
  VU u_carry_final0 = ShiftRight<kHalfShift>(u_sum0);
  VU u_sum1 = Add(u_carry_final0, u_col0);
  VU u_carry_final1 = ShiftRight<kHalfShift>(u_sum1);
  VU u_sum1_shifted = ShiftLeft<kHalfShift>(u_sum1);
  VU u_sum2 = Add(u_carry_final1, u_col2);
  VU u_carry_final2 = ShiftRight<kHalfShift>(u_sum2);
  VU u_sum3 = Add(u_carry_final2, u_col3);

  // Assemble final result
  VU u_result0 = And(u_sum0, u_low_mask);
  VU u_result2 = And(u_sum2, u_low_mask);
  VU u_result3 = ShiftLeft<kHalfShift>(u_sum3);

  VU u_n_hi = Add(u_result3, u_result2);
  VU u_n_lo = Add(u_sum1_shifted, u_result0);

  // =============================================================================
  // PHASE 5: Extract Quotient and Fractional Parts
  // =============================================================================

  // Extract integer quotient. 9 for F32, 12 for F64
  constexpr int kQuotientShift = ExponentBits<T>() + 1;
  VU u_shifted_n = ShiftRight<kQuotientShift>(u_n_hi);

  // fractional shifts derived from magic constants
  // F32: 5, 18, 14 (sum = 37, total with quotient = 46 = 2×23)
  // F64: 28, 24, 40 (sum = 92, total with quotient = 104 = 2×52)
  constexpr int kFracLowShift = kIsSingle ? 5 : 28;
  constexpr int kFracMidShift = kIsSingle ? 18 : 24;
  constexpr int kFracHighShift = kIsSingle ? 14 : 40;

  // Verify total shift constraint
  constexpr int kTotalShift =
      kQuotientShift + kFracLowShift + kFracMidShift + kFracHighShift;
  static_assert(kTotalShift == (kIsSingle ? 46 : 104),
                "Total shift must equal 2×mantissa_bits");

  // Extract fractional parts
  constexpr TU kFracMidMask = (static_cast<TU>(1) << kFracMidShift) - 1;
  VU u_frac_low_bits = And(u_n_lo, Set(du, kFracMidMask));
  VU u_shifted_sig_lo = ShiftLeft<kFracLowShift>(u_frac_low_bits);
  VU u_frac_mid_bits = ShiftRight<kFracMidShift>(u_n_lo);
  constexpr TU kFracHighMask =
      (static_cast<TU>(1) << (kFracHighShift - kFracLowShift)) - 1;
  VU u_frac_high_bits = And(u_n_hi, Set(du, kFracHighMask));

  // =============================================================================
  // PHASE 6: Conversion to Floating Point
  // =============================================================================
  // magic constants for branchless int→float conversion
  // Handle sign bit
  VU u_sign_bit = And(BitCast(du, x), Set(du, SignMask<T>()));
  VU u_exponent_part =
      Xor(u_sign_bit, BitCast(du, Set(d, static_cast<T>(1.0))));
  VU u_quotient_signed = Or(u_shifted_n, u_exponent_part);

  // Magic number conversion for quotient
  V shifter = Set(d, kIsSingle ? 0x1.8p15f : 0x1.8p43);
  V integer_part = Add(shifter, BitCast(d, u_quotient_signed));

  V n_hi = Sub(integer_part, shifter);
  n_hi = Sub(BitCast(d, u_quotient_signed), n_hi);

  // constants for fractional parts
  VU u_epsilon = BitCast(du, Set(d, kIsSingle ? 0x1p-23f : 0x1p-52));
  VU u_exp_mid = Xor(u_sign_bit, u_epsilon);
  VU u_shifted_sig_mid =
      Or(ShiftLeft<kFracHighShift>(u_frac_high_bits), u_frac_mid_bits);
  VU u_frac_mid_combined = Or(u_shifted_sig_mid, u_exp_mid);
  V shifter_mid = BitCast(d, u_exp_mid);
  V n_med = Sub(BitCast(d, u_frac_mid_combined), shifter_mid);

  VU u_epsilon_low = BitCast(du, Set(d, kIsSingle ? 0x1p-46f : 0x1p-104));
  VU u_exp_low = Xor(u_sign_bit, u_epsilon_low);
  VU u_frac_low_combined = Or(u_shifted_sig_lo, u_exp_low);

  V exp_low = BitCast(d, u_exp_low);
  V frac_low_combined = BitCast(d, u_frac_low_combined);

  V n = Add(n_hi, n_med);
  V n_lo = Sub(n_hi, n);
  n_lo = Add(n_med, n_lo);
  n_lo = Add(n_lo, Sub(frac_low_combined, exp_low));

  // =============================================================================
  // PHASE 7: Convert to Radians
  // =============================================================================

  // Multiply by 2π with error compensation (Cody-Waite multiplication)
  constexpr auto kPiMul2 = data::kPiMul2<T>;
  const V pi2_hi = Set(d, kPiMul2[0]);
  const V pi2_med = Set(d, kPiMul2[1]);

  V r = Mul(pi2_hi, n);
  V r_lo, r_w0, r_w1;
  if constexpr (!kNativeFMA && kIsSingle) {
    using DW = RepartitionToWide<D>;
    using DH = Half<D>;
    using VW = Vec<DW>;
    const DW dw;
    const DH dh;
    VW pi2_whi = Set(dw, data::kPiMul2<double>[0]);
    VW r0 = Mul(pi2_whi, PromoteUpperTo(dw, n));
    VW r1 = Mul(pi2_whi, PromoteLowerTo(dw, n));
    VW r_lo_w0 = Sub(r0, PromoteUpperTo(dw, r));
    VW r_lo_w1 = Sub(r1, PromoteLowerTo(dw, r));
    r_lo = Combine(d, DemoteTo(dh, r_lo_w0), DemoteTo(dh, r_lo_w1));
    r_w0 = BitCast(d, r0);
    r_w1 = BitCast(d, r1);
  } else if constexpr (!kNativeFMA) {
    // Without FMA, `MulSub(pi2_hi, n, r)` yields zero and drops the 0.5-ulp(r)
    // rounding error of r — worth 0.5 ulp of the result near k*pi/2. Recover
    // it from the exact head product (head - r is exact by Sterbenz).
    V head, rest;
    SplitMul(pi2_hi, n, head, rest);
    r_lo = Add(Sub(head, r), rest);
    r_lo = Add(Mul(pi2_med, n), r_lo);
  } else {
    r_lo = MulSub(pi2_hi, n, r);
    r_lo = MulAdd(pi2_med, n, r_lo);
  }
  r_lo = MulAdd(pi2_hi, n_lo, r_lo);

  // =============================================================================
  // PHASE 8: Small Argument Handling
  // =============================================================================

  const V min_input = Set(d, static_cast<T>(0x1p-20));
  const auto ismall_arg = Gt(min_input, abx);

  r = IfThenElse(ismall_arg, x, r);
  r_lo = IfThenElse(ismall_arg, Zero(d), r_lo);
  V r2 = Mul(r, r);

  // =============================================================================
  // PHASE 9: Table Lookup
  // =============================================================================

  // Generated by npsr/trig/data/approx.h.sol
  const T *table_base = OP == Operation::kCos ? data::kCosApproxTable<T>
                                              : data::kSinApproxTable<T>;

  // Calculate table index
  VU u_n_mask = Set(du, kIsSingle ? 0xFF : 0x1FF);
  VU u_index = And(BitCast(du, integer_part), u_n_mask);
  VI u_table_index = BitCast(di, ShiftLeft<2>(u_index));

  const V deriv_hi = GatherIndex(d, table_base, u_table_index);
  const V sigma = GatherIndex(d, table_base + 1, u_table_index);
  const V func_hi = GatherIndex(d, table_base + 2, u_table_index);
  const V func_lo = GatherIndex(d, table_base + 3, u_table_index);
  const V deriv = Add(deriv_hi, sigma);

  // =============================================================================
  // PHASE 10: Final Assembly
  // =============================================================================
  V res_hi_lo = MulAdd(sigma, r, func_hi);
  V res_hi, deriv_hi_r_cor;
  if constexpr (!kNativeFMA && !kIsSingle) {
    // Same substitution as in Phase 7. sigma is a signed power of two (see
    // approx.h) so sigma*r is exact, but deriv_hi*r would round under a
    // decayed MulAdd and corrupt the head; SplitMul recovers it.
    V dr, dr_rest;
    SplitMul(deriv_hi, r, dr, dr_rest);
    res_hi = Add(res_hi_lo, dr);
    V dr_hi = Sub(res_hi, res_hi_lo);
    deriv_hi_r_cor = Add(Sub(dr, dr_hi), dr_rest);
  } else {
    res_hi = MulAdd(deriv_hi, r, res_hi_lo);
    deriv_hi_r_cor = MulAdd(deriv_hi, r, Sub(res_hi_lo, res_hi));
  }
  V sum_cor = MulAdd(sigma, r, Sub(func_hi, res_hi_lo));
  V res_lo0 = Add(deriv_hi_r_cor, sum_cor);

  // Polynomial corrections
  V s2 = Set(d, kIsSingle ? 0x1.1110b8p-7f : 0x1.1110fabb3551cp-7);
  V s1 = Set(d, kIsSingle ? -0x1.555556p-3f : -0x1.5555555554448p-3);
  V sin_poly = MulAdd(s2, r2, s1);
  sin_poly = Mul(sin_poly, r2);
  sin_poly = Mul(sin_poly, r);

  V c1 = Set(d, kIsSingle ? 0x1.5554f8p-5f : 0x1.5555555554ccfp-5);
  const V neg_half = Set(d, static_cast<T>(-0.5));
  V cos_poly;
  if constexpr (kIsSingle) {
    cos_poly = MulAdd(c1, r2, neg_half);
  } else {
    V c2 = Set(d, -0x1.6c16ab163b2d7p-10);
    cos_poly = MulAdd(c2, r2, c1);
    cos_poly = MulAdd(cos_poly, r2, neg_half);
  }
  cos_poly = Mul(cos_poly, r2);

  V corr = NegMulAdd(func_hi, r, deriv);
  V res_lo_rlo = MulAdd(corr, r_lo, func_lo);
  V res_lo_sin = MulAdd(deriv, sin_poly, res_lo0);
  V res_lo_cos = MulAdd(func_hi, cos_poly, res_lo_sin);
  V res_lo = Add(res_lo_cos, res_lo_rlo);
  return Add(res_hi, res_lo);
}
// NOLINTNEXTLINE(google-readability-namespace-comments)
}  // namespace npsr::HWY_NAMESPACE::trig
HWY_AFTER_NAMESPACE();

#endif  // NPSR_TRIG_EXTENDED_INL_H_
