// Auto-generated by npsr/trig/data/constants.h.sol
// Use `spin sollya -f` to force regeneration
#ifndef NPSR_TRIG_DATA_CONSTANTS_H
#define NPSR_TRIG_DATA_CONSTANTS_H

namespace npsr::trig::data {
template <typename T, bool FMA> inline constexpr char kPi[] = {};
template <> inline constexpr float kPi<float, true>[] = {
0x1.921fb6p1f, -0x1.777a5cp-24f, -0x1.ee59dap-49f, };
template <> inline constexpr float kPi<float, false>[] = {
0x1.92p1f, 0x1.fb4p-11f, 0x1.444p-23f, 0x1.68c234p-38f, 
};
template <> inline constexpr double kPi<double, true>[] = {
0x1.921fb54442d18p1, 0x1.1a62633145c06p-53, 0x1.c1cd129024e09p-106, };
template <> inline constexpr double kPi<double, false>[] = {
0x1.921fb6p1, -0x1.777a5cp-24, -0x1.ee59dap-49, 0x1.98a2e03707345p-76, 
};

template <bool FMA> inline constexpr double kPiPrec35[] = {
0x1.921fb5444p1, 0x1.68c234c4c6628p-38, };
template <> inline constexpr double kPiPrec35<false>[] = {
0x1.921fb6p1, -0x1.777a5cp-24, -0x1.ee59dap-49, };

template <typename T> inline constexpr char kPiMul2[] = {};
template <> inline constexpr float kPiMul2<float>[] = {
0x1.921fb6p2f, -0x1.777a5cp-23f, };
template <> inline constexpr double kPiMul2<double>[] = {
0x1.921fb54442d18p2, 0x1.1a62633145c07p-52, };

template <bool FMA> inline constexpr double kPiDiv16Prec29[] = {
0x1.921fb54442d18p-3, 0x1.1a62633p-57, 0x1.45c06e0e68948p-89, };
template <> inline constexpr double kPiDiv16Prec29<false>[] = {
0x1.921fb54p-3, 0x1.10b461p-33, 0x1.a626331p-61, 0x1.1701b839a252p-91, 
};

template <typename T> inline constexpr char kInvPi = '_';
template <> inline constexpr float kInvPi<float> = 0x1.45f306p-2f;
template <> inline constexpr double kInvPi<double> = 0x1.45f306dc9c883p-2;

template <typename T> inline constexpr char kHalfPi = '_';
template <> inline constexpr float kHalfPi<float> = 0x1.921fb6p0f;
template <> inline constexpr double kHalfPi<double> = 0x1.921fb54442d18p0;

template <typename T> inline constexpr char k16DivPi = '_';
template <> inline constexpr float k16DivPi<float> = 0x1.45f306p2f;
template <> inline constexpr double k16DivPi<double> = 0x1.45f306dc9c883p2;

} // namespace npsr::trig::data

#endif // NPSR_TRIG_DATA_CONSTANTS_H
