// Auto-generated by npsr/trig/data/polyf32.h.sol
// Use `spin sollya -f` to force regeneration
#ifndef NPSR_TRIG_DATA_POLYF32_H
#define NPSR_TRIG_DATA_POLYF32_H

namespace npsr::trig::data {
// Degree-9 odd minimax sin(x) = x + x^3*P(x^2) on [2^-20, pi/2].
// Coefficients {c3, c5, c7, c9} for the f32 PolyLow in npsr/trig/low-inl.h.
// See poly.h.sol for the recipe, pins and measured worst cases.
template <bool FMA> inline constexpr float kSinPolyLowF32[] = {
-0x1.555544p-3f, 0x1.110d94p-7f, -0x1.9f3644p-13f, 0x1.5a9eap-19f, 
};
template <bool FMA> inline constexpr float kCosPolyLowF32[] = {
-0x1.555548p-3f, 0x1.110e34p-7f, -0x1.9f527cp-13f, 0x1.5c1b4p-19f, 
};
template <> inline constexpr float kSinPolyLowF32<false>[] = {
-0x1.55554ap-3f, 0x1.110e88p-7f, -0x1.9f621ap-13f, 0x1.5cfce2p-19f, 
};
template <> inline constexpr float kCosPolyLowF32<false>[] = {
-0x1.55554ap-3f, 0x1.110e9p-7f, -0x1.9f653ep-13f, 0x1.5d3afep-19f, 
};

// Degree-9 odd minimax sin(r) on [2^-30, pi/2 + 0.012] for the f32 High path
// in trig/high-inl.h; c1 is fitted, not pinned to 1. See poly.h.sol.
// Relative error 9.64818894863128662109375e-2 ulp(f32). Coefficients {c1, c3, c5, c7, c9}.
inline constexpr double kSinPolyHighF32[] = {
0x1.ffffffce99ecep-1, -0x1.5555471207a17p-3, 0x1.110e5bbaaff44p-7, 
-0x1.9f5e996744e9ep-13, 0x1.5ce7e229f1f1p-19, };

} // namespace npsr::trig::data

#endif // NPSR_TRIG_DATA_POLYF32_H
